services:
  - type: web
    name: ghost
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    disk:
      name: ghost-content
      mountPath: /var/lib/ghost/content
      sizeGB: 1
